CREATE TABLE DBTEAMPROJECT(
	`UID`	INT	NOT NULL	COMMENT '사용자식별ID',
	`UNUM`	INT	NOT NULL	COMMENT '사용자 학번',
	`UNAME`	VARCHAR(20)	NOT NULL	COMMENT '사용자 이름',
	`UPNO`	INT	NOT NULL	COMMENT '사용자 연락처',
	`CHECKOUT`	BOOLEAN	NOT NULL	COMMENT '사용자 대출 가능여부',
	`UPWD`	VARCHAR(20)	NOT NULL	COMMENT '사용자 비밀번호',
	`Field`	VARCHAR(255)	NULL,
    PRIMARY KEY (`UID`)
);