DROP TABLE if exists USER;
CREATE TABLE USER(
UID INT NOT NULL AUTO_INCREMENT COMMENT '사용자식별ID',
UNUM VARCHAR(20) NOT NULL COMMENT '사용자 학번',
UNAME VARCHAR(20) NOT NULL COMMENT '사용자 이름',
UPNO VARCHAR(20) NOT NULL COMMENT '사용자 연락처',
CHECKOUT BOOLEAN NOT NULL default true COMMENT '사용자 대출 가능여부',
UPWD VARCHAR(20) NOT NULL COMMENT '사용자 비밀번호',
PRIMARY KEY (UID)
);

drop table if exists Book;
CREATE TABLE Book (
book_title VARCHAR(100) NOT NULL,
book_author VARCHAR(50) NOT NULL,
publisher VARCHAR(50) NOT NULL,
publishing_year DATE NOT NULL,
book_account INT NOT NULL,
book_rent_yn DATE NULL,
book_id INT NOT NULL,
UID INT NOT NULL AUTO_INCREMENT ,
PRIMARY KEY (UID)
);

drop table if exists Admin;
CREATE TABLE Admin (
UID INT NOT NULL AUTO_INCREMENT ,
book_num2 INT NOT NULL ,
UID2 INT NOT NULL ,
UNAME VARCHAR(20) NOT NULL ,
UPWD VARCHAR(20) NOT NULL ,
PRIMARY KEY (UID)
);